# Generated by Django 5.1.1 on 2024-09-15 06:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_post_author_post_views_post_visitors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='visitors',
        ),
        migrations.AddField(
            model_name='post',
            name='visitors',
            field=models.ManyToManyField(blank=True, related_name='post_visitors', to=settings.AUTH_USER_MODEL),
        ),
    ]
